
name="$1"
path="$2"

if [[ "${path}" = "" ]];
then
    path="${name}"
    name=$(basename "${path}")
fi

mkdir -p $name
cd $name
cp ../../go.mod .
go get $path

srcDir=$(go mod download -json $path | grep '"Dir"' | awk -F '"' '{print $4}')
echo "srcDir -> $srcDir"
../../bin/devtools export -dir "${srcDir}" -gotemplate ../lib.tpl $path > $name.go

echo -e "# Generated by makelib.sh. DO NOT modify\n.PHONY: lib\nlib:\n\tgo build -buildmode=plugin -o $name.so" > makefile
make
